### ISSUE TITLE
add CLA etc and LICENSE 

### ISSUE THREAD

**Issue by stevemcghee** [ameer00/Building-Reliable-Platforms-on-GCP-with-Google-SRE#5]
eg https://github.com/r9y-dev/r9y-map/blob/main/CONTRIBUTING.md

**Comment by stevemcghee** [comment]
1) need to install workflow/app:
https://github.com/apps/google-cla

2) enable branch protection

https://g3doc.corp.google.com/company/teams/opensource/cla/github.md?cl=head

**Comment by stevemcghee** [comment]
i think i need to be a repo owner for the app install. @ameer00

**Comment by stevemcghee** [comment]
@ameer00 you have to install the App:  https://github.com/apps/google-cla

**Comment by ameer00** [comment]
done
